SHSCRIPTS += addpackage
SHSCRIPTS += view-freebsd-port
SHSCRIPTS += view-port
SHSCRIPTS += devserv
SHSCRIPTS += install
SHSCRIPTS += darwin-chroot
SHSCRIPTS += darwin-chroot-alt
SHSCRIPTS += homes/Darwin/.profile
SHSCRIPTS += homes/Darwin/.profile-alt

check:
	shellcheck $(SHSCRIPTS)
