SHSCRIPTS += addpackage
SHSCRIPTS += view-freebsd-port
SHSCRIPTS += view-port
SHSCRIPTS += devserv
SHSCRIPTS += install
SHSCRIPTS += darwin-chroot
SHSCRIPTS += homes/Darwin/.profile

check:
	shellcheck $(SHSCRIPTS)
